#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: gitlabtestapp
#  namespace: argocd
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/Khaddan/gitlab-test.git
#    targetRevision: HEAD
#    path: services  # Le dossier contenant les YAML K8s (ajuste si tu les mets dans un sous-dossier k8s/)
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: ecommerce
#  syncPolicy:
#    syncOptions:
#      - CreateNamespace=true
#    automated:
#      selfHeal: true
#      prune: true
