
apiVersion: v1
kind: test1-service
metadata:
  name: test1-service
spec:
  selector:
    app: test1-service
  ports:
    - port: 9991
      targetPort: 9991
  type: ClusterIP
---

apiVersion: v1
kind: test2-service
metadata:
  name: test2-service
spec:
  selector:
    app: test2-service
  ports:
    - port: 9909
      targetPort: 9909
  type: ClusterIP
---